name: Behat

on:
  pull_request:
    paths:
      #- '.github/workflows/**'
      #- 'appinfo/**'
      #- 'lib/**'
      #- 'templates/**'
      #- 'tests/**'
      #- 'vendor/**'
      #- 'vendor-bin/**'
      #- '.php-cs-fixer.dist.php'
      #- 'composer.json'
      #- 'composer.lock'

  push:
    branches:
      - main
      - master
      - stable*

permissions:
  contents: read

concurrency:
  group: behat-sqlite-encryption${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  # Location of the behat.yml file
  BEHAT_CONFIG: ./tests/Integration/config/behat.yml

jobs:
  behat-sqlite-encryption:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: ['8.1', '8.2']
        server-versions: ['stable25', 'stable26', 'master']
        exclude:
          - php-versions: '8.1'
            server-versions: 'stable25'
          - php-versions: '8.2'
            server-versions: 'stable25'

    steps:
      - name: Set app env
        run: |
          # Split and keep last
          echo "APP_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV

      - name: Checkout server
        uses: actions/checkout@v3
        with:
          submodules: true
          repository: nextcloud/server
          ref: ${{ matrix.server-versions }}

      - name: Checkout circles app
        uses: actions/checkout@v3
        with:
          repository: nextcloud/circles
          path: apps/circles
          ref: ${{ matrix.server-versions }}

      - name: Checkout app
        uses: actions/checkout@v3
        with:
          path: apps/${{ env.APP_NAME }}

      - name: Set up php ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, iconv, fileinfo, intl, sqlite, pdo_sqlite, apcu
          ini-values:
            apc.enable_cli=on
          coverage: none

      - name: Install composer dependencies
        working-directory: apps/${{ env.APP_NAME }}
        run: composer i

      - name: Set up Nextcloud
        env:
          DB_PORT: 4444
        run: |
          mkdir data
          echo '<?php $CONFIG=["memcache.local"=>"\OC\Memcache\APCu","hashing_default_password"=>true];' > config/config.php
          ./occ maintenance:install --verbose --database=sqlite --database-name=nextcloud --database-host=127.0.0.1 --database-port=$DB_PORT --database-user=root --database-pass=rootpassword --admin-user admin --admin-pass admin
          ./occ config:system:set --value="http://localhost:8080" -- overwrite.cli.url
          ./occ app:enable --force circles
          ./occ app:enable --force ${{ env.APP_NAME }}
          for user in alice bob jane john; do \
          OC_PASS="$user" ./occ user:add --password-from-env "$user"; \
          done
          ./occ group:add "Bobs Group"
          for user in bob jane; do \
          OC_PASS="$user" ./occ group:adduser "Bobs Group" "$user"; \
          done

      - name: Enable server-side encryption
        run: |
          ./occ app:enable encryption
          ./occ encryption:enable

      - name: Run Nextcloud
        run: php -S localhost:8080 &

      - name: Behat integration
        working-directory: apps/${{ env.APP_NAME }}
        run: ./vendor/bin/behat --config=${{ env.BEHAT_CONFIG }} --profile ci

  summary:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: behat-sqlite-encryption

    if: always()

    name: behat-sqlite-encryption-summary

    steps:
      - name: Summary status
        run: if ${{ needs.behat-sqlite-encryption.result != 'success' }}; then exit 1; fi
